import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/ui/navbar'

export const metadata: Metadata = {
  title: 'Vo Phu Phat | My Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-beauSans flex flex-col bg-background">
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
