import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/ui/navbar'
import { Poppins } from 'next/font/google'
import { cn } from '@/lib/utils'
import Footer from '@/components/ui/footer'

const poppins = Poppins({ weight: ['100', '200', '300', '400', '500', '600', '700'], subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Vo Phu Phat | My Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("flex flex-col bg-background", poppins.className)}>
        < Navbar />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html >
  )
}
